### ISSUE TITLE
Bug parsing an article's XML

### ISSUE THREAD

**Issue by andresgsaravia** [andresgsaravia/research-engine#156]
I just tried to add an article (doi:10.1086/309571) to the library and got the following error:

```
list index out of range
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~research-engine/0.370752145895514202/src/bibliography.py", line 191, in post
    metadata = parse_xml(item_dom, kind)
  File "/base/data/home/apps/s~research-engine/0.370752145895514202/src/bibliography.py", line 54, in parse_xml
    res["date"] = dom.getElementsByTagName("journal_issue")[0].getElementsByTagName("year")[0].childNodes[0].nodeValue
IndexError: list index out of range
```

It seems parsing Crossref's XML is still going to be a problem...

**Comment by andresgsaravia** [comment]
And yet another one with a similar error 10.1086/118137
